spring:
  application:
    name: JobIT

  datasource:
    url: jdbc:mysql://localhost:3306/it_job
    username: root
    password: 123456

  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    open-in-view: false

  main:
    allow-circular-references: true
